from selenium import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
import unittest


class NewVisitorTest(unittest.TestCase):

	def setUp(self):
		#Cannot add firefox binary to PATH (no admin privileges on employee computer)
		self.binary = FirefoxBinary(firefox_path = r'C:\Users\w23209\AppData\Local\Mozilla Firefox\firefox.exe')
		self.browser = webdriver.Firefox(firefox_binary=self.binary)

	def tearDown(self):
		self.browser.quit()

	def test_start_list_and_retrieve_later(self):
		#Someone wants to open new online to-do app. 
		#User is checking out its homepage
		self.browser.get('http://localhost:8000')
		
		#User sees that page title mention to-do list
		self.assertIn('To-Do', self.browser.title)
		self.fail('Finish the test!')

#User is invited to enter a to-do item straight away

#User types "Develop functional test for your to-do app" into a text box

#After user hits enter, the page updates, and now the page lists
#1: Develop functional test for your to-do app" as an item in a to-do list

#Text box inviting user to add another item is stil visible
#User enters "Use your test to check if app is working"

#The page updates again, and now shows both items on the list

#User list will be remembered and unique URL to the user list is generated by site
#Some text which exlpain it

#User visit the URL and list is still there

#User closes the site

if __name__ == '__main__':
	unittest.main(warnings='ignore')
